### ISSUE TITLE
Use versioning appropriately via assembly attributes and AppVeyor.yml

### ISSUE THREAD

**Issue by luigiberrettini** [graffen/NLog.Targets.Syslog#65]
## Semantic versioning
3.0.2(-\<prerelease>)(+\<buildnumber>)

## AssemblyInfo versioning
**AssemblyVersion**
3.0.0

**AssemblyFileVersion**
3.1.0.\<APPVEYOR_BUILD_NUMBER>

**AssemblyInformationalVersion**
3.1.0(-\<prerelease>)

## Info
It could be useful to rely on AppVeyor cmdlets:
```powershell
Update-AppveyorBuild -Version "$major.$minor.$patch.$env:APPVEYOR_BUILD_NUMBER"
Set-AppveyorBuildVariable -Name <string> -Value <string>
```

Maybe it is sufficient to perform AssemblyInfo patching in AppVeyor:
```yml
assembly_info:
    patch: true
    file: MyVersion.cs
    assembly_version: '$(assembly_version)'
    assembly_file_version: '$(appveyor_build_version)'
    assembly_informational_version: '$(assembly_info_version)'
```

**Links**
 - http://semver.org
 - https://github.com/StevenThuriot/Snippets/blob/master/AppVeyor/Patch%20Assembly%20Version.ps1
 - https://www.appveyor.com/docs/build-worker-api/#set-environment-variable
 - https://gist.github.com/FeodorFitsner/e038821e3e46e3df0e8f
 - http://help.appveyor.com/discussions/problems/5926useenvironmentvariableinversion
 - http://stackoverflow.com/questions/826777/how-to-have-an-auto-incrementing-version-number-visual-studio
 - http://stackoverflow.com/questions/3279235/net-assemblyname-version-build-versus-revision
 - http://stackoverflow.com/questions/64602/what-are-differences-between-assemblyversion-assemblyfileversion-and-assemblyin

## Notice about `major.minor.build.revision`
**BUILD**
Refers to the build number in a software product, not the number of times you run a build!
Different build numbers can be used:
 - when source code changes for hotfix updates of a `major.minor.{build - 1}` version (build number increased by 1)
 - when source code is the same and processor/platform/compiler change

**REVISION**
Refers to the revision number in a software product, not not the number of times you run a build!
Different revision numbers can be used:
 - when source code changes hotfix updates of a `major.minor.build.{revision - 1}` version (revision number increased by 1)
 - only when assemblies are fully interchangeable with other assemblies having a different revision number

## Task list
- [x] Use the right attributes in AssemblyInfo.cs
- [x] Use AssemblyInformationalVersion to retrieve version during build script execution
- [x] Use Update-AppveyorBuild to set AppVeyor build version on the basis of AssemblyInfo version
- [x] Patch AssemblyInfo.cs, on AppVeyor build, changing only AssemblyFileVersion

**Comment by luigiberrettini** [comment]
- [ ] Use the right attributes in AssemblyInfo.cs
- [ ] Use AssemblyInformationalVersion to retrieve version during manual build
- [ ] Use Update-AppveyorBuild to set AppVeyor build version on the basis of AssemblyInfo version
- [ ] Patch AssemblyInfo.cs, on AppVeyor build, changing only AssemblyFileVersion

**Comment by luigiberrettini** [comment]
## Notice about `major.minor.build.revision`
**BUILD**
Refers to the build number in a software product, not the number of times you run a build!
Different build numbers can be used:
 - when source code changes for hotfix updates of a `major.minor.{build - 1}` version (build number increased by 1)
 - when source code is the same and processor/platform/compiler change

**REVISION**
Refers to the revision number in a software product, not not the number of times you run a build!
Different revision numbers can be used:
 - when source code changes hotfix updates of a `major.minor.build.{revision - 1}` version (revision number increased by 1)
 - only when assemblies are fully interchangeable with other assemblies having a different revision number
